trigger: none

resources:
  repositories:
    - repository: appCode
      type: git
      name: myproject/netflix
      ref: main
    
    - repository: gitOpsRepo
      type: github
      endpoint: github-conn
      name: muzzammil-hamdu/netflix-argocd-deploy-helm
      ref: main

variables:
  dockerHubUser: "mujju752"
  imageName: "netflix"
  valuesFile: "charts/netflix/values.yaml"

stages:

# -------------------------------------------------------
# 1) BUILD & PUSH DOCKER IMAGE
# -------------------------------------------------------
- stage: Build
  displayName: "Build and Push Image"
  jobs:
    - job: BuildImage
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: appCode
          persistCredentials: false
          clean: true

        - script: |
            echo "Building Netflix application..."
            ls -la
          displayName: "Verify Application Code"

        - task: Docker@2
          displayName: "Build & Push Docker Image"
          inputs:
            command: buildAndPush
            containerRegistry: dockerhub-conn
            repository: "$(dockerHubUser)/$(imageName)"
            dockerfile: "**/Dockerfile"
            tags: |
              $(Build.BuildId)
              latest


# -------------------------------------------------------
# 2) UPDATE GITOPS REPO
# -------------------------------------------------------
- stage: UpdateGitOps
  dependsOn: Build
  displayName: "Update GitOps Repository"

  jobs:
    - job: UpdateGitHub
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: gitOpsRepo
          persistCredentials: true
          clean: true

        - script: |
            sudo apt-get update -y
            sudo snap install yq
          displayName: "Install yq"

        - script: |
            echo "Validating GitOps directory..."
            ls -la
          displayName: "Verify GitOps Repo"

        - script: |
            echo "Updating Helm values.yaml..."
            yq -i '
              .image.repository = "$(dockerHubUser)/$(imageName)" |
              .image.tag = "$(Build.BuildId)"
            ' "$(valuesFile)"

            echo "Updated values.yaml:"
            cat "$(valuesFile)"
          displayName: "Update values.yaml"

        - script: |
            git config user.email "azurepipeline@devops.com"
            git config user.name "Azure Pipeline Bot"

            git add "$(valuesFile)"

            if git diff --staged --quiet; then
              echo "No changes detected — skipping commit."
              exit 0
            fi

            git commit -m "🚀 Deploy: $(dockerHubUser)/$(imageName):$(Build.BuildId)"
            git push origin main
          displayName: "Commit and Push"



# -------------------------------------------------------
# 3) VALIDATE ROLLOUT (After ArgoCD Auto Sync)
# -------------------------------------------------------
- stage: Validate
  dependsOn: UpdateGitOps
  displayName: "Validate Kubernetes Rollout"

  jobs:
    - job: ValidateApp
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: gitOpsRepo
          persistCredentials: true
          clean: true

        - script: |
            echo "Waiting 90 seconds for ArgoCD to sync deployment..."
            sleep 90
          displayName: "Wait for ArgoCD Sync"

        - script: |
            echo "Checking Kubernetes rollout..."

            if ! kubectl get namespace netflix &> /dev/null; then
              echo "❌ Namespace netflix not found"
              kubectl get namespaces
              exit 1
            fi

            DEPLOY=$(kubectl get deploy -n netflix -o jsonpath='{.items[0].metadata.name}')
            READY=$(kubectl get deploy $DEPLOY -n netflix -o jsonpath='{.status.readyReplicas}')
            DESIRED=$(kubectl get deploy $DEPLOY -n netflix -o jsonpath='{.spec.replicas}')

            echo "Ready: $READY / Desired: $DESIRED"

            if [ "$READY" == "$DESIRED" ]; then
              echo "✅ Deployment Healthy"
              exit 0
            fi
            
            echo "❌ Deployment Failed"
            exit 1
          continueOnError: true
          displayName: "Validate Deployment"


        # ---------- AUTO ROLLBACK ----------
        - script: |
            echo "⚠ Deploy Failed — Rolling Back..."

            git fetch --all
            PREVIOUS=$(git log -n 10 --pretty=format:"%s" | grep "Deploy:" | sed -n '2p' | awk '{print $2}')

            if [ -z "$PREVIOUS" ]; then
              echo "⚠ No previous version — rolling back to 'latest'"
              NEWTAG="latest"
            else
              NEWTAG="$PREVIOUS"
            fi

            echo "Rollback to Image: $NEWTAG"

            yq -i ".image.tag = \"$NEWTAG\"" "$(valuesFile)"

            git config user.email "azurepipeline@devops.com"
            git config user.name "Azure Pipeline Bot"
            git add "$(valuesFile)"
            git commit -m "🔄 ROLLBACK to $NEWTAG"
            git push origin main

          condition: failed()
          displayName: "Automatic Rollback"
