trigger: none

resources:
  repositories:
    - repository: appCode
      type: git
      name: myproject/netflix
      ref: main
    
    - repository: gitOpsRepo
      type: github
      endpoint: github-conn
      name: muzzammil-hamdu/netflix-argocd-deploy-helm
      ref: main

variables:
  dockerHubUser: "mujju752"
  imageName: "netflix"
  valuesFile: "charts/netflix/values.yaml"
  argocdServer: "4.220.46.113"
  argocdUsername: "admin"
  argocdPassword: "24cdDusPoHSVnbtc"
  dockerHubPassword: "YOUR_DOCKERHUB_PASSWORD"
  prometheusURL: "http://4.220.4.31:9090"
  grafanaURL: "http://4.220.4.31:3000"
  alertmanagerURL: "http://4.220.4.31:9093"

stages:

- stage: Build
  displayName: "Build and Push Image"
  jobs:
    - job: BuildImage
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: appCode
          persistCredentials: false
          clean: true

        - script: |
            echo "Building Netflix application from Azure Repos"
            ls -la
          displayName: "Verify Application Code"

        - task: Docker@2
          displayName: "Build and Push Docker Image"
          inputs:
            command: buildAndPush
            containerRegistry: dockerhub-conn
            repository: "$(dockerHubUser)/$(imageName)"
            dockerfile: "**/Dockerfile"
            tags: |
              $(Build.BuildId)
              latest

- stage: UpdateGitOps
  dependsOn: Build
  displayName: "Update GitHub GitOps Repo"

  jobs:
    - job: UpdateGitHub
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: gitOpsRepo
          persistCredentials: true
          clean: true

        - script: |
            echo "Checking if Kubernetes namespace 'netflix' exists..."
            if kubectl get namespace netflix >/dev/null 2>&1; then
              echo "✔ Namespace 'netflix' already exists"
            else
              echo "❌ Namespace not found — creating now..."
              kubectl create namespace netflix
              echo "✔ Namespace 'netflix' created successfully"
            fi
            echo ""
            echo "Current namespaces:"
            kubectl get ns
          displayName: "Create Namespace If Missing"

        - script: |
            sudo apt-get update -y
            sudo snap install yq
          displayName: "Install yq"

        - script: |
            echo "Working in GitHub GitOps repository"
            echo "Repository: muzzammil-hamdu/netflix-argocd-deploy-helm"
            ls -la
            
            if [ -d "charts/netflix" ]; then
              ls -la charts/netflix/
            else
              echo "Warning: charts/netflix directory not found"
              find . -type d -name "netflix" 2>/dev/null
            fi
          displayName: "Verify GitOps Repository"

        - script: |
            echo "Verifying values.yaml exists..."
            
            if [ ! -f "$(valuesFile)" ]; then
              echo "ERROR: $(valuesFile) not found"
              find . -name "values.yaml" -type f
              exit 1
            fi
            
            echo "Found values.yaml"
            echo "Current content:"
            cat "$(valuesFile)"
          displayName: "Verify values.yaml"

        - script: |
            echo "=== DEBUG: Pipeline Variables ==="
            echo "Build.BuildId: $(Build.BuildId)"
            echo "dockerHubUser: $(dockerHubUser)"
            echo "imageName: $(imageName)"
            echo "valuesFile: $(valuesFile)"
            echo ""
            
            if [ -z "$(Build.BuildId)" ]; then
              echo "ERROR: Build.BuildId is empty!"
              exit 1
            fi
          displayName: "Debug: Check Variables"

        - script: |
            echo "Updating values.yaml with new image..."
            echo "Build ID: $(Build.BuildId)"
            echo "Docker Hub User: $(dockerHubUser)"
            echo "Image Name: $(imageName)"
            echo "New image: $(dockerHubUser)/$(imageName):$(Build.BuildId)"
            
            echo ""
            echo "Current values.yaml:"
            cat "$(valuesFile)"
            
            echo ""
            echo "Updating repository..."
            yq -i '.image.repository = "$(dockerHubUser)/$(imageName)"' "$(valuesFile)"
            
            echo "Updating tag..."
            yq -i '.image.tag = "$(Build.BuildId)"' "$(valuesFile)"

            echo ""
            echo "Updated values.yaml:"
            cat "$(valuesFile)"
            
            echo ""
            echo "Verifying image values:"
            echo "Repository: $(yq '.image.repository' $(valuesFile))"
            echo "Tag: $(yq '.image.tag' $(valuesFile))"
          displayName: "Update values.yaml"

        - script: |
            echo "Configuring Git..."
            git config user.email "azurepipeline@devops.com"
            git config user.name "Azure Pipeline Bot"
            
            echo "Staging changes..."
            git add "$(valuesFile)"
            
            if git diff --staged --quiet; then
              echo "No changes to commit"
              exit 0
            fi

            echo "Committing changes..."
            git commit -m "Deploy: $(dockerHubUser)/$(imageName):$(Build.BuildId)"

            echo "Pushing to GitHub..."
            git push origin main
            
            echo "Successfully pushed to GitHub"
          displayName: "Commit and Push to GitHub"

- stage: CreateArgoApp
  dependsOn: UpdateGitOps
  displayName: "Create ArgoCD Application"

  jobs:
    - job: CreateApp
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: gitOpsRepo
          persistCredentials: true
          clean: true

        - script: |
            echo "=== Creating/Updating ArgoCD Application ==="
            
            if [ -f "netflix-app.yaml" ]; then
              echo "Found netflix-app.yaml, applying..."
              kubectl apply -f netflix-app.yaml
              echo "✓ ArgoCD Application created/updated"
            else
              echo "Creating ArgoCD Application..."
              cat <<EOF | kubectl apply -f -
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: netflix
              namespace: argocd
            spec:
              project: default
              source:
                repoURL: https://github.com/muzzammil-hamdu/netflix-argocd-deploy-helm
                targetRevision: main
                path: charts/netflix
                helm:
                  releaseName: netflix
              destination:
                server: https://kubernetes.default.svc
                namespace: netflix
              syncPolicy:
                automated:
                  prune: true
                  selfHeal: true
                syncOptions:
                - CreateNamespace=true
            EOF
              echo "✓ ArgoCD Application created"
            fi
            
            echo ""
            echo "Verifying Application exists..."
            kubectl get application netflix -n argocd
            
            echo ""
            echo "=== Creating Docker Registry Secret ==="
            
            # Check if secret exists
            if kubectl get secret dockerhub-secret -n netflix &>/dev/null; then
              echo "✓ Docker registry secret already exists"
            else
              echo "Creating docker registry secret..."
              kubectl create secret docker-registry dockerhub-secret \
                --docker-server=docker.io \
                --docker-username=$(dockerHubUser) \
                --docker-password=$(dockerHubPassword) \
                --docker-email=devops@netflix.local \
                -n netflix
              echo "✓ Docker registry secret created"
            fi
            
            # Patch service account to use the secret
            kubectl patch serviceaccount default -n netflix \
              -p '{"imagePullSecrets": [{"name": "dockerhub-secret"}]}' 2>/dev/null || true
              
            echo "✓ Service account patched"
          displayName: "Apply ArgoCD Application"

- stage: Validate
  dependsOn: CreateArgoApp
  displayName: "Validate or Rollback"

  jobs:
    - job: ValidateApp
      pool:
        name: projectpool
        demands: agent.name -equals projectagent

      steps:
        - checkout: gitOpsRepo
          persistCredentials: true
          clean: true

        - script: |
            echo "=== Checking ArgoCD Setup ==="
            
            echo "Logging in with admin credentials..."
            argocd login $(argocdServer) --username $(argocdUsername) --password $(argocdPassword) --insecure --grpc-web
            
            echo ""
            echo "Listing ArgoCD applications..."
            argocd app list --insecure --grpc-web || echo "Warning: Could not list apps"
            
            echo ""
            echo "Checking if netflix app exists..."
            argocd app get netflix --insecure --grpc-web || echo "WARNING: netflix app not found in ArgoCD"
            
            echo ""
            echo "Syncing Netflix application..."
            argocd app sync netflix --prune --insecure --grpc-web || echo "WARNING: Sync command failed"
            
            echo ""
            echo "Waiting for sync to complete (up to 5 minutes)..."
            argocd app wait netflix --timeout 300 --insecure --grpc-web || echo "WARNING: App wait timeout"
            
            echo ""
            echo "Final app status:"
            argocd app get netflix --insecure --grpc-web
            
            echo "ArgoCD sync complete"
          displayName: "Trigger ArgoCD Sync"
          continueOnError: true

        - script: |
            echo "Waiting 30 seconds for deployment to stabilize..."
            sleep 30
          displayName: "Wait for Deployment Stabilization"

        - script: |
            echo "=== DEBUG: ArgoCD Application Status ==="
            kubectl get application netflix -n argocd -o wide
            echo ""
            echo "Application sync status:"
            kubectl get application netflix -n argocd -o jsonpath='{.status.sync.status}'
            echo ""
            echo "Application health:"
            kubectl get application netflix -n argocd -o jsonpath='{.status.health.status}'
            echo ""
            echo "Full Application details:"
            kubectl describe application netflix -n argocd
            echo ""
            echo "Last sync result:"
            kubectl get application netflix -n argocd -o jsonpath='{.status.operationState.phase}'
          displayName: "Debug: Check ArgoCD Application"
          continueOnError: true

        - script: |
            echo "=== Manual ArgoCD Sync ==="
            
            echo "Logging in with admin credentials..."
            argocd login $(argocdServer) --username $(argocdUsername) --password $(argocdPassword) --insecure --grpc-web
            
            echo ""
            echo "Checking ArgoCD connectivity..."
            argocd app list --insecure --grpc-web
            
            echo ""
            echo "Getting app status..."
            argocd app get netflix --insecure --grpc-web
            
            echo ""
            echo "Forcing sync..."
            argocd app sync netflix --prune --insecure --grpc-web
            
            echo ""
            echo "Waiting for sync..."
            sleep 30
            
            echo ""
            echo "Checking status after sync..."
            argocd app get netflix --insecure --grpc-web
          displayName: "Manual ArgoCD Sync"
          continueOnError: true

        - script: |
            echo "=== Validating Kubernetes Deployment ==="
            
            if ! kubectl get namespace netflix &>/dev/null; then
              echo "❌ Namespace netflix does not exist"
              kubectl get namespaces
              exit 1
            fi
            
            echo "✔ Namespace exists"
            
            echo "All resources in netflix namespace:"
            kubectl get all -n netflix
            echo ""
            
            DEPLOY_COUNT=$(kubectl get deploy -n netflix --no-headers 2>/dev/null | wc -l)
            if [ "$DEPLOY_COUNT" -eq 0 ]; then
              echo "❌ No deployments found in netflix namespace"
              echo "Checking pod events:"
              kubectl get events -n netflix --sort-by='.lastTimestamp' | tail -20
              exit 1
            fi
            
            echo "✔ Found $DEPLOY_COUNT deployment(s)"
            
            DEPLOY_NAME=$(kubectl get deploy -n netflix -o jsonpath='{.items[0].metadata.name}')
            echo "Checking deployment: $DEPLOY_NAME"
            
            DESIRED=$(kubectl get deploy $DEPLOY_NAME -n netflix -o jsonpath='{.spec.replicas}')
            READY=$(kubectl get deploy $DEPLOY_NAME -n netflix -o jsonpath='{.status.readyReplicas}')
            UNAVAILABLE=$(kubectl get deploy $DEPLOY_NAME -n netflix -o jsonpath='{.status.unavailableReplicas}')
            
            echo "Desired replicas: ${DESIRED:-0}"
            echo "Ready replicas: ${READY:-0}"
            echo "Unavailable replicas: ${UNAVAILABLE:-0}"
            
            if [ "${READY:-0}" -eq "${DESIRED:-0}" ] && [ -z "$UNAVAILABLE" ]; then
              echo ""
              echo "✔ DEPLOYMENT SUCCESSFUL"
              kubectl get pods -n netflix
              exit 0
            else
              echo ""
              echo "❌ DEPLOYMENT FAILED"
              kubectl get pods -n netflix
              kubectl describe pods -n netflix
              exit 1
            fi
          name: healthCheck
          continueOnError: true
          displayName: "Validate Deployment"

        - script: |
            echo "=== INITIATING ROLLBACK ==="
            
            if ! command -v yq &> /dev/null; then
              sudo snap install yq
            fi
            
            git fetch --unshallow 2>/dev/null || git fetch --all
            
            PREVIOUS=$(git log -n 10 --pretty=format:"%s" | grep "Deploy:" | grep -oP '(?<=: )[^ ]+' | sed -n '2p')
            
            if [ -z "$PREVIOUS" ]; then
              echo "No previous deployment found, rolling back to latest"
              REPO="$(dockerHubUser)/$(imageName)"
              TAG="latest"
            else
              echo "Found previous deployment: $PREVIOUS"
              REPO=$(echo $PREVIOUS | cut -d ':' -f1)
              TAG=$(echo $PREVIOUS | cut -d ':' -f2)
            fi
            
            echo "Rolling back to: $REPO:$TAG"
            
            yq -i ".image.repository = \"$REPO\" | .image.tag = \"$TAG\"" "$(valuesFile)"
            
            echo "Rolled back values.yaml:"
            cat "$(valuesFile)"
            
            git config user.email "azurepipeline@devops.com"
            git config user.name "Azure Pipeline Bot"
            git add "$(valuesFile)"
            git commit -m "ROLLBACK to $REPO:$TAG - Build $(Build.BuildId) failed"
            
            git push origin main
            
            echo "Rollback pushed to GitHub"
            
            sleep 30
            
            echo ""
            echo "=== Syncing rollback with ArgoCD ==="
            argocd login $(argocdServer) --username $(argocdUsername) --password $(argocdPassword) --insecure --grpc-web
            argocd app sync netflix --prune --insecure --grpc-web
            argocd app wait netflix --timeout 300 --insecure --grpc-web
            
            echo ""
            echo "Status after rollback:"
            kubectl get deployments -n netflix
            kubectl get pods -n netflix
            
          condition: failed()
          displayName: "Automatic Rollback"
