apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netflix-secret
  namespace: default
spec:
  encryptedData:
    TMDB_KEY: <ENCRYPTED-VALUE-GENERATED-BY-KUBESEAL>
  template:
    metadata:
      name: netflix-secret
      namespace: default
