---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netflix-secret
  namespace: default
spec:
  encryptedData:
    TMDB_KEY: AgCksmxBXU9SGkn60cVvh34mONmNcLhTkQB4/rbC0xHhB34OGjVos0KvNPHc5mjyHUCTgTZtNaPpdlMXcOrl9lrkq058v0cisybkADJTDAFBcbjr4th6CiRdQ417BIVRF/tpGxB8xmdwR7AmW9gw9vNGbHZx8yOyKSQxdszvUOQmul3MvpeKUnwwUy+GPl99sGEoabFzUIDTxNRC1JaXfKQvz0smhRrZ4rHAl1EpnrdbYCZKCJmF7f67+5oLT4gEQ0PVAvFKUazbTnT3ibys7MBWgzdiv+qznv0Zii6P/y3qJhJfkcomPNjUlv2rGAz5LXNQ/uVrJ7cVt1EB0Hkrm4wWZ7zwT6nn1Ur3/jU3jM2gHQi+MUUK+JCbrPojD9oCCJNCdchjqoda7Oy7oDrNw4RbYAXf4ygvznR/BitH8rfsQ8EBHbgw7LLB927QNGTO/1cN8hhZTB809bE5r83LCTU72mv7ENnGYCjYpN606UwCNiKdpI4ivjB+r+mbOHpWa/hKWNAG4H0t4L2G5QhOVhFvZt6s9wp9CyGZzNc1QYGAv54PidTVV8leMpn3Kt0Gdlv20zo93UiX9XP4dBSO3AQu9jlXFRdygJSCekFPLXOLZ/gvgGo5gcdPCG097Pb9pRgK0Xx2f9g91xxdD1eKF2dQTcYMUu4j/Bj3SouhyqdDjDvLCHIisOiGbVq0CEpAKxhIPv6RCfGvyuG67ALd+Ip+GsL//G5E55bKPFpi15S+GA==
  template:
    metadata:
      name: netflix-secret
      namespace: default
    type: Opaque
