apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netflix-servicemonitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: netflix-app
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
